//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_list
    {
        public int order_id { get; set; }
        public int store_id { get; set; }
        public System.DateTime ordered_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
