//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cart_id { get; set; }
        public int order_id { get; set; }
        public string product { get; set; }
        public int box { get; set; }
        public int each { get; set; }
        public int pound { get; set; }
        public Nullable<decimal> price { get; set; }
        public string market { get; set; }
        public string note { get; set; }
        public string route { get; set; }
    }
}
