//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public int store_id { get; set; }
        public string store_name { get; set; }
        public string store_phone { get; set; }
        public string store_address { get; set; }
        public string contact_name { get; set; }
        public string contact_phone { get; set; }
        public string store_detail { get; set; }
        public string store_fax { get; set; }
        public byte isMarket { get; set; }
    }
}
